Refactor into separate charts
MissionCriticalCloud/cosmic-microservices-chart pull request #14
Opened 2017-04-07 13:33 UTC by bheuvel

2017-04-10 12:21 UTC, eliasgomes requested changes

2017-04-10 12:21 UTC, eliasgomes commented on charts/cosmic-common/Chart.yaml
> +name: cosmic-common
`cosmic-commons` with an `S` ?

2017-04-10 12:21 UTC, eliasgomes commented on charts/cosmic-common/templates/_helpers.tpl
> +{{/* vim: set filetype=mustache: */}}
These `_helpers.tpl` are not being used, maybe remove them?

2017-04-10 12:21 UTC, eliasgomes commented on charts/cosmic-common/templates/configmap.yaml
> +{{- if .Values.namespace }}
Just keep the global namespace for simplicity?

2017-04-10 12:21 UTC, eliasgomes commented on charts/cosmic-config-server/templates/_cosmic-config-server.json.tpl
> +{{- define "secrets.cosmic-config-files.cosmic-config-server.json" -}}
With this new chart structure, I'd suggest to review our template naming strategy.

2017-04-10 12:21 UTC, eliasgomes commented on charts/cosmic-config-server/templates/deployment.yaml
> +  name: {{ .Chart.Name }}
I'd suggest to remove this helm (deployments and pods) labeling for now.

2017-04-10 12:21 UTC, eliasgomes commented on charts/cosmic-config-server/templates/deployment.yaml
> +        imagePullPolicy: {{ .Values.image.pullPolicy }}
We should review our _case_ policy, at the moment we have camel-cased and underscore separated.

2017-04-11 08:07 UTC, eliasgomes requested changes

2017-04-11 08:07 UTC, eliasgomes commented on charts/cosmic-vault/templates/_helpers.tpl
> +{{/* vim: set filetype=mustache: */}}
There's still a `_helper.tpl` trying to sneak in :)

2017-04-11 08:07 UTC, eliasgomes commented on charts/cosmic-vault/templates/deployment.yaml
> +{{- range $index, $node := .Values.service.ports }}
Here we're not using `$index`

2017-04-11 08:07 UTC, eliasgomes commented on charts/elasticsearch/templates/deployment.yaml
> +{{- range $index, $node := .Values.service.ports }}
Here we're not using `$index`

2017-04-11 08:07 UTC, eliasgomes commented on charts/cosmic-usage-api/templates/deployment.yaml
> +{{- range $index, $node := .Values.service.ports }}
Here we're not using `$index`

2017-04-11 08:07 UTC, eliasgomes commented on charts/cosmic-usage-ui/values.yaml
> +usageApiBaseUrl:  # for example: https://localhost:8080/   <-- don't forget the slash at the end
New line missing

2017-04-11 08:07 UTC, eliasgomes commented on charts/cosmic-usage-ui/templates/deployment.yaml
> +          name: init-container-scripts
New line missing

2017-04-11 08:07 UTC, eliasgomes commented on charts/cosmic-vault/templates/deployment.yaml
> +          name: cosmic-vault-files
New line missing

2017-04-11 08:07 UTC, eliasgomes commented on charts/elasticsearch/values.yaml
> +
Extra new line :D

2017-04-11 08:07 UTC, eliasgomes commented on charts/logstash/templates/deployment.yaml
> +{{- if or .Values.devMode (and .Values.global .Values.global.devMode) }}
Same places we're checking for `devMode` like `if .Values.global.devMode` and some places like this: `if or .Values.devMode (and .Values.global .Values.global.devMode)`. Maybe using only the global one?

2017-04-11 08:07 UTC, eliasgomes commented on charts/cosmic-metrics-collector/values.yaml
> +
Extra new line

2017-04-11 10:05 UTC, bheuvel commented on charts/cosmic-usage-ui/values.yaml
> +usageApiBaseUrl:  # for example: https://localhost:8080/   <-- don't forget the slash at the end
Added...

2017-04-11 10:25 UTC, bheuvel commented
@eliasgomes a.k.a. "hawk eye" 😉 , thanks for the review. Adjusted additional comments.

2017-04-11 11:40 UTC, eliasgomes approved these changes

2017-04-11 11:41 UTC, eliasgomes commented
@bheuvel thanks for patience! :P

2017-04-11 11:41 UTC, merged