Implement a Helm repo from this github repo
MissionCriticalCloud/cosmic-microservices-chart pull request #17
Opened 2017-04-20 19:10 UTC by bheuvel

To enable serving the tgz files, the repo needs to enable `GitHub Pages`, serving from the `/docs` folder.

The general README has been adjusted to explain the usage of this (Helm) repo.
The `cosmic-microservices-chart` chart has been renamed to `cosmic-usage-chart`.
Grafana has been added to the _usage_ collection, and was partly the reason for implementing this repo.

Result is that implementation/usage of the `cosmic-usage-chart`, does not require a checkout of the charts source folder. Just add this (link to this) repo and use `helm install`.

2017-04-21 09:43 UTC, borisroman requested changes
Store artifacts on S3

2017-04-21 09:43 UTC, borisroman commented on cosmic/microservices/cosmic-common/values.yaml
> +  namespace:
\n

2017-04-21 09:43 UTC, borisroman commented on cosmic/microservices/cosmic-config-server/values.yaml
> +    backend:
\n

2017-04-21 09:43 UTC, borisroman commented on cosmic/microservices/cosmic-metrics-collector/values.yaml
> +    readOnlyToken:
\n

2017-04-21 09:43 UTC, borisroman commented on cosmic/microservices/cosmic-usage-api/values.yaml
> +    readOnlyToken:
\n

2017-04-21 09:43 UTC, borisroman commented on custom/cosmic-vault/values.yaml
> +  namespace:
\n

2017-04-21 09:43 UTC, borisroman commented on custom/rabbitmq/values.yaml
> +
\n

2017-04-21 09:48 UTC, bheuvel commented on cosmic/microservices/cosmic-common/values.yaml
> +  namespace:
Done

2017-04-21 09:48 UTC, bheuvel commented on cosmic/microservices/cosmic-config-server/values.yaml
> +    backend:
Done

2017-04-21 09:48 UTC, bheuvel commented on cosmic/microservices/cosmic-metrics-collector/values.yaml
> +    readOnlyToken:
Done

2017-04-21 09:48 UTC, bheuvel commented on cosmic/microservices/cosmic-usage-api/values.yaml
> +    readOnlyToken:
Done

2017-04-21 09:48 UTC, bheuvel commented on custom/cosmic-vault/values.yaml
> +  namespace:
Done

2017-04-28 13:50 UTC, bheuvel commented
go build

2017-04-28 13:53 UTC, bheuvel commented
go build

2017-04-28 13:59 UTC, bheuvel commented
go build

2017-04-28 14:08 UTC, bheuvel commented
go build

2017-04-28 14:13 UTC, bheuvel commented
go build

2017-05-01 08:37 UTC, merged