Extend deployments for bubble-toolkit
MissionCriticalCloud/cosmic-microservices-chart pull request #2
Opened 2017-03-20 09:13 UTC by bheuvel

Option for private registry
Add cosmic-vault and config loading when in dev-mode (bubble-toolkit)

2017-03-20 15:05 UTC, eliasgomes requested changes

2017-03-20 15:05 UTC, eliasgomes commented on templates/configmaps/_init-container.yaml
> +  cosmic-usage-api-config.json: |
All this new files should only be provided in "dev" mode.

2017-03-20 15:05 UTC, eliasgomes commented on templates/configmaps/init-container-files/_post-vault-config.sh.tpl
> +    /bin/sh /scripts/readiness-probe.sh -h ${host} -p ${port} -P "/v1/secret/${endpoint}" -H "${headers}" -x 1
Can't we just leave out the `/bin/sh ` part?

2017-03-20 15:05 UTC, eliasgomes commented on templates/configmaps/init-container-files/_post-vault-config.sh.tpl
> +        /bin/sh /scripts/readiness-probe.sh -m POST -h ${host} -p ${port} -P "/v1/secret/${endpoint}" -s 204 -b "${body}" -H "${headers}\nContent-Type: application/json\nContent-Length: ${body_length
Please see comment above.

2017-03-20 15:05 UTC, eliasgomes commented on templates/configmaps/init-container-files/_post-vault-config.sh.tpl
> +host='localhost'
I'd add an empty line before this one for better a better reading experience ;)

2017-03-20 15:05 UTC, eliasgomes commented on templates/configmaps/init-container-files/_readiness-probe.sh.tpl
> +  printf "${method} ${path} ${protocol}\nHost: ${host}\n${headers}\n\n${body}\n"
Won't the `set -x` instruction already do that (print the computed string)?

2017-03-20 15:05 UTC, eliasgomes commented on templates/deployments/_cosmic-config-server.yaml
> +              "name": "install",
Shall we change this init-container's name to something like: `vault-health`?

2017-03-20 15:05 UTC, eliasgomes commented on templates/deployments/_cosmic-vault.yaml
> +  namespace: cosmic
We should replace this hard-coded namespace with a placeholder.

2017-03-20 15:05 UTC, eliasgomes commented on templates/services/_cosmic-vault.yaml
> +  namespace: cosmic
We should replace this hard-coded namespace with a placeholder.

2017-03-20 15:05 UTC, eliasgomes commented on templates/cosmic-microservices.yaml
> +{{- range .Values.namespaces -}}
We're including namespaces templates at this point, but I haven't seen any namespace templates. Are we missing something?

2017-03-20 15:05 UTC, eliasgomes commented on templates/configmaps/init-container-files/_readiness-probe.sh.tpl
> +  echo "Result returned from remote host:"
Isn't the `set -x` instruction also showing `nc`'s output?

2017-03-20 15:10 UTC, eliasgomes commented on templates/cosmic-microservices.yaml
> +{{- range .Values.namespaces -}}
Also, last time I checked, creating a namespace the already existed would fail when installing a chart.

2017-03-20 15:16 UTC, bheuvel commented on templates/configmaps/init-container-files/_post-vault-config.sh.tpl
> +    /bin/sh /scripts/readiness-probe.sh -h ${host} -p ${port} -P "/v1/secret/${endpoint}" -H "${headers}" -x 1
Files are not created with execute bit set and filesystem is read-only.

2017-03-20 15:16 UTC, bheuvel commented on templates/configmaps/init-container-files/_post-vault-config.sh.tpl
> +        /bin/sh /scripts/readiness-probe.sh -m POST -h ${host} -p ${port} -P "/v1/secret/${endpoint}" -s 204 -b "${body}" -H "${headers}\nContent-Type: application/json\nContent-Length: ${body_length
Files are not created with execute bit set and filesystem is read-only.

2017-03-20 15:17 UTC, bheuvel commented on templates/configmaps/init-container-files/_readiness-probe.sh.tpl
> +  printf "${method} ${path} ${protocol}\nHost: ${host}\n${headers}\n\n${body}\n"
Product of extended debugging, will indeed clean up

2017-03-20 15:18 UTC, bheuvel commented on templates/configmaps/init-container-files/_readiness-probe.sh.tpl
> +  echo "Result returned from remote host:"
No, the commands are echo-ed by `-x`, not the intermediate pipe results.
Was also done for extended troubleshooting, will remove it

2017-03-20 15:19 UTC, bheuvel commented on templates/deployments/_cosmic-config-server.yaml
> +              "name": "install",
Will do

2017-03-20 15:20 UTC, bheuvel commented on templates/deployments/_cosmic-vault.yaml
> +  namespace: cosmic
Will also use `.Values.namespaces`

2017-03-20 15:20 UTC, bheuvel commented on templates/services/_cosmic-vault.yaml
> +  namespace: cosmic
Will also use `.Values.namespaces`

2017-03-20 15:22 UTC, bheuvel commented on templates/cosmic-microservices.yaml
> +{{- range .Values.namespaces -}}
Indeed found out was missing a file, will add it.
Will have another look at the namespace

2017-03-21 12:42 UTC, eliasgomes requested changes
Can you please add `.idea` to `.gitignore` and remove those files (and folder) from version control?

2017-03-21 13:46 UTC, eliasgomes approved these changes

2017-03-21 13:47 UTC, merged